apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: radwahesham/hello
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}